[package]
name = "dye-planner"
version = "0.1.0"
authors = [ "Eric Frisino <code@worthcommitting.com>" ]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"